INSERT INTO dbo.Authors (AuthorName) VALUES
('Greta L. Sorenson'),
('Miles J. Halberg'),
('Anita K. Vang'),
('Trevor R. Lindholm'),
('Sophie J. Marquette'),
('Daniel P. Olesen'),
('Riley M. Strand'),
('Helena J. Kappel'),
('Owen T. Bjornstad'),
('Marla R. Nystrom'),
('Gavin J. Solheim'),
('Erin L. Dahlgren'),
('Nora P. Sundstrom'),
('Caleb R. Mikkelson'),
('Tara J. Volden'),
('Henry K. Riemer'),
('Lena M. Schreiber'),
('Joel A. Paulson'),
('Kara L. Gunderson'),
('Mason J. Thorsen'),
('Elise R. Halverson'),
('Peter J. Melby'),
('Hannah K. Odegard'),
('Marcus L. Kjelstrom'),
('Vivian R. Hartmann');

INSERT INTO dbo.Publishers (PublisherName) VALUES
('Northwoods Lantern Press'),
('Prairie Hearth Publishing'),
('Great Lakes Storyhouse'),
('Twin Pines Literary'),
('Badger & Bluff Books'),
('Iron Range Romance Co.'),
('Snowline Fiction Works'),
('Harborlight Collective'),
('Coulee Ridge Editions'),
('Capitol River House'),
('Sugarbush & Stone'),
('Red Barn Meadow Press'),
('Taconite Trail Publishing'),
('Peninsula Heartline'),
('Gopher State Ink'),
('Driftless Valley Books'),
('Lake Superior Quill'),
('North Prairie Tales'),
('Icewind Story Co.'),
('Blue Earth River Press'),
('Door County Narrative'),
('Twin Cities Ember'),
('Prairie Skyline House'),
('Ironwood & Ivy Literary'),
('Bluffside Romance Works');

INSERT INTO dbo.RomanceNovels
(Title, AuthorId, PublicationYear, Pages, PublisherId, SettingCity, SettingState, Protagonists, RomanceTropes, OneLiner)
VALUES
('Winter Promises in Marquette', 1, 2024, 312, 1, 'Marquette', 'MI', 'Chef & Snowplow Driver', 'Slow burn; winter romance', 'A stranded chef finds warmth with a snowplow driver during a Lake Superior freeze.'),
('Love Under the Lift Bridge in Duluth', 2, 2023, 298, 2, 'Duluth', 'MN', 'Engineer & Tour Guide', 'Workplace romance', 'A bridge engineer falls for the guide who knows every secret of the harbor.'),
('Romance at the Fargo Film Fest', 3, 2022, 276, 3, 'Fargo', 'ND', 'Filmmaker & Critic', 'Enemies-to-lovers', 'A harsh critic and a hopeful filmmaker clash until the spotlight softens them both.'),
('Hearts of the Hayward Highlands', 4, 2021, 344, 4, 'Hayward', 'WI', 'Hiker & Park Ranger', 'Outdoor adventure', 'A ranger rescues a lost hiker and discovers she’s exactly what he’s been missing.'),
('The Wintry Roads to Ironwood', 5, 2020, 259, 5, 'Ironwood', 'MI', 'Paramedic & Carpenter', 'Healing romance', 'A paramedic rebuilding her life meets a carpenter rebuilding his hometown.'),
('Love Songs of St. Cloud', 6, 2019, 288, 6, 'St. Cloud', 'MN', 'Choir Director & Music Teacher', 'Small town; cozy', 'Two music teachers harmonize their way into each other’s hearts.'),
('Romance at the Red Wing Pottery Works', 7, 2024, 333, 7, 'Red Wing', 'MN', 'Ceramic Artist & Historian', 'Creative romance', 'A pottery artist and a historian uncover a legacy—and unexpected love.'),
('The Ashland Lighthouse Vow', 8, 2023, 301, 8, 'Ashland', 'WI', 'Lighthouse Keeper & Journalist', 'Mystery; slow burn', 'A journalist investigates a lighthouse legend and falls for its keeper.'),
('Love Beneath the Soo Locks', 9, 2022, 355, 9, 'Sault Ste. Marie', 'MI', 'Ship Captain & Dockworker', 'Forbidden romance', 'A captain and a dockworker navigate dangerous waters of duty and desire.'),
('Romance in the Rapids of Eau Claire', 10, 2021, 276, 10, 'Eau Claire', 'WI', 'Kayaker & EMT', 'Adventure; meet-cute', 'A rescue on the river sparks something deeper than adrenaline.'),
('Hearts of the Bemidji Blue', 11, 2020, 318, 11, 'Bemidji', 'MN', 'Painter & Librarian', 'Quiet romance', 'A painter finds his muse in the librarian who restores his confidence.'),
('Love at the La Crosse Market', 12, 2019, 292, 12, 'La Crosse', 'WI', 'Vendor & Chef', 'Food romance', 'A chef and a vendor compete for customers but find a recipe for love.'),
('Romance on the Minocqua Lakes', 13, 2018, 270, 13, 'Minocqua', 'WI', 'Fishing Guide & Photographer', 'Opposites attract', 'A fishing guide teaches a city photographer how to see the lake with new eyes.'),
('The St. Paul Snowfall Pact', 14, 2024, 347, 14, 'St. Paul', 'MN', 'Paramedic & Architect', 'Second chance', 'A paramedic and an architect reconnect during a record-breaking snowfall.'),
('Love at the Madison Winter Market', 15, 2023, 243, 15, 'Madison', 'WI', 'Baker & Woodworker', 'Cozy romance', 'A baker and a woodworker craft something sweet together.'),
('Romance in the Driftless Hills of Decorah', 16, 2022, 329, 16, 'Decorah', 'IA', 'Naturalist & Teacher', 'Nature romance', 'A naturalist guides a teacher through hidden valleys—and unexpected feelings.'),
('Hearts Along the North Shore Trail', 17, 2021, 284, 17, 'Grand Marais', 'MN', 'Trail Builder & Writer', 'Outdoorsy; slow burn', 'A writer hiking the North Shore meets the builder who maintains the trail.'),
('Love at the Superior Ice Caves', 18, 2020, 256, 18, 'Bayfield', 'WI', 'Guide & Geologist', 'Adventure; forced proximity', 'A cave collapse forces two explorers to rely on each other.'),
('Romance in the Moorhead Corn Maze', 19, 2019, 275, 19, 'Moorhead', 'MN', 'Farmer & Event Planner', 'Small town; comedic', 'A planner gets lost in more ways than one while organizing a fall festival.'),
('The Duluth Harbor Promise', 20, 2018, 298, 20, 'Duluth', 'MN', 'Harbor Pilot & Café Owner', 'Community romance', 'A harbor pilot finds comfort in the café owner who knows everyone’s story.'),
('Love Under the Rhinelander Pines', 21, 2024, 310, 21, 'Rhinelander', 'WI', 'Forester & Nurse', 'Healing; outdoorsy', 'A forester recovering from injury meets the nurse who helps him heal.'),
('Romance at the Minot Winter Carnival', 22, 2023, 333, 22, 'Minot', 'ND', 'Ice Sculptor & Teacher', 'Festival romance', 'A sculptor and a teacher carve out time for each other.'),
('Hearts of the Hibbing Highlands', 23, 2022, 276, 23, 'Hibbing', 'MN', 'Miner & Café Server', 'Blue-collar romance', 'A miner finds unexpected warmth in a café server’s kindness.'),
('Love on the Prairie Roads of Brookings', 24, 2021, 241, 24, 'Brookings', 'SD', 'Mechanic & Grad Student', 'Road trip; opposites attract', 'A breakdown leads to a breakthrough for two unlikely travelers.'),
('Romance in the Winona Riverlight', 25, 2020, 288, 25, 'Winona', 'MN', 'River Guide & Poet', 'Artistic romance', 'A poet finds inspiration in the river guide who knows every bend of the water.');
